import { Applicant } from "./types/applicant-tracking.type";

export const applicantsData: Applicant[] = [
  {
    id: "1",
    applicantId: 1234,
    fullname: "John Doe",
    jobTitle: "Software Developer",
    department: "Engineering",
    status: "Pending",
    email: "john.doe@example.com",
    phoneNo: "09123456789",
  },
  {
    id: "2",
    applicantId: 1235,
    fullname: "Jane Smith",
    jobTitle: "HR Specialist",
    department: "Human Resources",
    status: "Pending",
    email: "jane.smith@example.com",
    phoneNo: "09123456788",
  },
  {
    id: "3",
    applicantId: 1236,
    fullname: "Michael Johnson",
    jobTitle: "Product Manager",
    department: "Product",
    status: "Interview Scheduled",
    email: "michael.johnson@example.com",
    phoneNo: "09123456787",
  },
  {
    id: "4",
    applicantId: 1237,
    fullname: "Emily White",
    jobTitle: "Marketing Specialist",
    department: "Marketing",
    status: "Offer Extended",
    email: "emily.white@example.com",
    phoneNo: "09123456786",
  },
  {
    id: "5",
    applicantId: 1238,
    fullname: "David Lee",
    jobTitle: "UX Designer",
    department: "Design",
    status: "Pending",
    email: "david.lee@example.com",
    phoneNo: "09123456785",
  },
  {
    id: "6",
    applicantId: 1239,
    fullname: "Sarah Williams",
    jobTitle: "QA Engineer",
    department: "Engineering",
    status: "Interview Scheduled",
    email: "sarah.williams@example.com",
    phoneNo: "09123456784",
  },
  {
    id: "7",
    applicantId: 1240,
    fullname: "James Brown",
    jobTitle: "Data Scientist",
    department: "Data Analytics",
    status: "Rejected",
    email: "james.brown@example.com",
    phoneNo: "09123456783",
  },
  {
    id: "8",
    applicantId: 1241,
    fullname: "Isabella Green",
    jobTitle: "Content Writer",
    department: "Marketing",
    status: "Pending",
    email: "isabella.green@example.com",
    phoneNo: "09123456782",
  },
];
