import { EmployeeOnboarding } from "../types/onboarding.type";

export const onboardingData: EmployeeOnboarding[] = [
  {
    id: "1",
    fullname: "John Doe",
    jobTitle: "Software Developer",
    department: "Engineering",
    status: "Pending",
    email: "john.doe@example.com",
    phoneNo: "09123456789",
    requiredFiles: {
      Resume: "Uploaded",
      "Valid ID": "Pending",
      "SSS ID": "Uploaded",
      PhilHealth: "Pending",
    },
  },
  {
    id: "2",
    fullname: "Jane Smith",
    jobTitle: "HR Specialist",
    department: "Human Resources",
    status: "Completed",
    email: "jane.smith@example.com",
    phoneNo: "09123456788",
    requiredFiles: {
      Resume: "Uploaded",
      "Valid ID": "Uploaded",
      "SSS ID": "Uploaded",
      PhilHealth: "Uploaded",
    },
  },
  {
    id: "3",
    fullname: "Alice Johnson",
    jobTitle: "Product Manager",
    department: "Product",
    status: "Completed",
    email: "alice.johnson@example.com",
    phoneNo: "09123456787",
    requiredFiles: {
      Resume: "Uploaded",
      "Valid ID": "Uploaded",
      "SSS ID": "Uploaded",
      PhilHealth: "Uploaded",
    },
  },
  {
    id: "4",
    fullname: "Bob Brown",
    jobTitle: "Marketing Specialist",
    department: "Marketing",
    status: "Pending",
    email: "bob.brown@example.com",
    phoneNo: "09123456786",
    requiredFiles: {
      Resume: "Pending",
      "Valid ID": "Uploaded",
      "SSS ID": "Pending",
      PhilHealth: "Pending",
    },
  },
  {
    id: "5",
    fullname: "Charlie Davis",
    jobTitle: "Sales Executive",
    department: "Sales",
    status: "In Progress",
    email: "charlie.davis@example.com",
    phoneNo: "09123456785",
    requiredFiles: {
      Resume: "Uploaded",
      "Valid ID": "Pending",
      "SSS ID": "Uploaded",
      PhilHealth: "Pending",
    },
  },
];
